# Generated by Django 4.2.3 on 2023-08-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_commerce_computer_philosophy_psychology_science'),
    ]

    operations = [
        migrations.DeleteModel(
            name='commerce',
        ),
        migrations.DeleteModel(
            name='computer',
        ),
        migrations.DeleteModel(
            name='philosophy',
        ),
        migrations.DeleteModel(
            name='psychology',
        ),
        migrations.DeleteModel(
            name='science',
        ),
    ]
