# Generated by Django 4.2.3 on 2023-08-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_delete_commerce_delete_computer_delete_philosophy_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='courses',
            new_name='pcourses',
        ),
    ]
