# Generated by Django 4.2.3 on 2023-08-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseModel',
        ),
        migrations.DeleteModel(
            name='DepartmentModel',
        ),
    ]
